### ISSUE TITLE
support laravel and lumen 6

### ISSUE THREAD

**Issue by ingen2** [pearlkrishn/lumen-request-validate#10]
composer error: 
  Problem 1
    - Conclusion: don't install laravel/lumen-framework v6.0.2
    - Conclusion: don't install laravel/lumen-framework v6.0.1
    - Conclusion: don't install laravel/lumen-framework v6.0.0
    - pearl/lumen-request-validate 1.3.0 requires laravel/lumen-framework 5.7.* || 5.8.* -> satisfiable by laravel/lumen-framework[5.7.x-dev, 5.8.x-dev].
    - pearl/lumen-request-validate 1.3.1 requires laravel/lumen-framework 5.7.* || 5.8.* -> satisfiable by laravel/lumen-framework[5.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/lumen-framework[6.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/lumen-framework[6.x-dev, 5.8.x-dev].
    - Installation request for laravel/lumen-framework ^6.0 -> satisfiable by laravel/lumen-framework[6.x-dev, v6.0.0, v6.0.1, v6.0.2].
    - Installation request for pearl/lumen-request-validate ^1.3 -> satisfiable by pearl/lumen-request-validate[1.3.0, 1.3.1].

**Comment by yoerriwalstra** [comment]
@pearlkrishn does this have your intention? Please let us know if you intend to pick up this issue or not.

**Comment by pearlkrishn** [comment]
#11
