### ISSUE TITLE
Support Lumen v10

### ISSUE THREAD

**Issue by Slisarenko** [pearlkrishn/lumen-request-validate#20]
Could you please add the ability to integrate your "pearlkrishn/lumen-request-validate" package 
with Lumen framework version 10?

**Comment by Slisarenko** [comment]
@pearlkrishn A [PR-21](https://github.com/pearlkrishn/lumen-request-validate/pull/21) was created

**Comment by pearlkrishn** [comment]
> @pearlkrishn A [PR-21](https://github.com/pearlkrishn/lumen-request-validate/pull/21) was created

Merged
